/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_burzum_timewheel_TimeWheel */

#ifndef _Included_com_burzum_timewheel_TimeWheel
#define _Included_com_burzum_timewheel_TimeWheel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_burzum_timewheel_TimeWheel
 * Method:    initTimeWheel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_burzum_timewheel_TimeWheel_initTimeWheel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_burzum_timewheel_TimeWheel
 * Method:    addTask
 * Signature: (Lcom/burzum/timewheel/TimeWheelNodeInterface;)J
 */
JNIEXPORT jlong JNICALL Java_com_burzum_timewheel_TimeWheel_addTask
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_burzum_timewheel_TimeWheel
 * Method:    removeTask
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_burzum_timewheel_TimeWheel_removeTask
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_burzum_timewheel_TimeWheel
 * Method:    stopTimeWheel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_burzum_timewheel_TimeWheel_stopTimeWheel
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
